name: CI

on:
  push:
    branches: ["feature/*", "main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    name: Tests (py${{ matrix.python-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install package + test deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest --cov=biometaprep --cov-report=term-missing
